Tags Now Working
UniversityOfFloridaACM/WebAPP pull request #19
Opened 2016-09-17 19:08 UTC by progdude

2016-10-09 02:24 UTC, andrewjkerr requested changes
Hey @progdude, @nicolasiscoding asked me to review this PR in order for it to be merged. I've left a few comments of things that should be fixed before merging. Let me know if you have any questions!

2016-10-09 02:24 UTC, andrewjkerr commented on app/routes.js
> +    // const basic = auth.basic({
Normally when using git or some other version control system, you don't comment out code to "remove" it since it's tracked in git.

2016-10-09 02:24 UTC, andrewjkerr commented on app/routes.js
> +    app.get('/repo', (req, res) => {
This page _probably_ shouldn't be unprotected. Is there a reason why you removed the basic auth?

2016-10-09 02:24 UTC, andrewjkerr commented on app/routes.js
> +
Nix the space here; inconsistent with coding standards.

2016-10-09 02:24 UTC, andrewjkerr commented on app/routes.js
> +                  path: __dirname + '/../localStorage/pdfs/' + req.body.pdfs[i],
Weird spacing here; please tab over to the left to make it consistent.

2016-10-09 02:24 UTC, andrewjkerr commented on app/routes.js
> +        res.send('');
Is there a reason why we're not sending anything back?

2016-10-09 02:24 UTC, andrewjkerr commented on app/routes.js
> +        res.zip(pdfs);
Inconsistent indentation here as well.

2016-10-09 02:24 UTC, andrewjkerr commented on app/routes.js
> +        // User.find({}, (err, users) => {
See my note above about commenting out code :)

2016-10-09 02:24 UTC, andrewjkerr commented on app/routes.js
> +    app.get('/getTags',  (req, res) => {
When you're building an API, you don't have the HTTP verb in the route name. In this case, you should have the following routes relating to tags:
- `GET /tags` to get the tags
- `POST(/PUT) /tags` to set the tags

2016-10-09 02:24 UTC, andrewjkerr commented on views/resume/profile_resume.ejs
> +
Weird spacing here; we should be as consistent as possible across all of the files. :)

2016-10-09 02:24 UTC, andrewjkerr commented on views/resume/repo.ejs
> +  <datalist id="languages">
Some of these aren't necessarily "languages"; I would update the div id to something more accurate like `skills`.

2016-10-09 02:24 UTC, andrewjkerr commented on views/resume/repo.ejs
> +                   $.post( "/getStudentResumes", $("#search").val(), function(data){
Spacing seems off here too.

2016-10-22 00:38 UTC, nicolasiscoding commented on app/routes.js
> +    app.get('/repo', (req, res) => {
Doing PR's, we can revisit this later. Currently doing manual dumps. I want the basic functionality

2016-10-22 00:39 UTC, nicolasiscoding commented on app/routes.js
> +    // const basic = auth.basic({
will fix

2016-11-28 15:19 UTC, nicolasiscoding commented
Its already November, @andrewjkerr @progdude is this tested and ready to be merged?

2016-11-28 16:46 UTC, andrewjkerr commented
My comments haven't been addressed so I don't think this is ready to be merged. Plus there are merge conflicts which will need to be fixed.

2018-02-01 17:48 UTC, closed without merging